export const TEXT = {
  vi: {
    skipLink: "Bỏ qua điều hướng",
    homeLabel: "LAVIECO, về trang chủ",
    primaryNavLabel: "Điều hướng chính",
    items: {
      story: { label: "Câu chuyện", hint: "Vì sao vỏ sò không phải rác" },
      programs: { label: "Chương trình", hint: "Học bằng đôi tay" },
      collection: { label: "Bộ sưu tập", hint: "Bằng chứng nhỏ, ý nghĩa lớn" },
      handbook: { label: "Cẩm nang", hint: "Cẩm nang xanh số · miễn phí trọn đời" },
      impact: { label: "Tác động", hint: "Từ Cần Thơ ra biển lớn" },
    },
    cta: "Hợp tác cùng chúng tôi",
    menu: {
      openLabel: "Mở Mục Lục Triển Lãm",
      closeLabel: "Đóng lại",
      dialogLabel: "Mục lục triển lãm số",
      kicker: "Mục lục triển lãm số",
      previewTitle: "The Living Gallery",
      previewPlace: "Cần Thơ · Mekong",
      previewNumber: "Nº 001 · Cần Thơ",
      previewQuote: "“Vỏ sò qua nét nghệ thuật tái sinh”",
      quote: "“Make it your life, through art.”",
      place: "Can Tho · Vietnam",
      facebook: "Facebook ↗",
      tiktok: "TikTok ↗",
      languageLabel: "Ngôn ngữ",
      items: {
        preface: "Lời tựa & triển lãm",
        story: "Câu chuyện: vỏ sò & sinh kế",
        programs: "Bốn nấc thang giáo dục",
        collection: "Bộ sưu tập vật phẩm minh chứng",
        handbook: "Cẩm nang xanh số",
        impact: "Tác động xã hội & tiêu dùng xanh",
        team: "Sáu người kể chuyện",
        contact: "Cánh cửa đồng hành & liên hệ",
      },
    },
    footer: {
      description:
        "Dự án Giáo dục Mỹ thuật Xanh (Green Art Education). Thí điểm tại Cần Thơ, tái định nghĩa phụ phẩm vỏ thủy hải sản ven sông Mekong thành tác phẩm nghệ thuật và bài học cộng đồng.",
      mottoLabel: "Phương châm",
      motto: "“Cuộc sống, qua từng nét nghệ thuật” / “Make it your life, through art.”",
      catalogueNumber: "Nº 001 · Phù sa & lúa nước",
      spaceTitle: "Không gian",
      links: {
        preface: "Lời tựa triển lãm",
        journey: "Từ vỏ đến tác phẩm",
        programs: "Bốn nấc thang giá trị",
        collection: "Vật phẩm minh chứng",
        handbook: "Cẩm nang xanh số",
        impact: "Tác động bền vững",
        team: "Sáu người kể chuyện",
      },
      coordinatesTitle: "Tọa độ kết nối",
      address: "Quận Ninh Kiều, TP. Cần Thơ, Việt Nam",
      hours: "Thứ Ba – Chủ Nhật · 09:00–18:00",
      connectTitle: "Kết nối",
      facebook: "Facebook ↗",
      tiktok: "TikTok ↗",
      wordmark: "LAVIECO",
      copyright: "© 2026 LAVIECO. Mọi tác quyền giáo dục và nghệ thuật được bảo lưu.",
      credit: "Thiết kế theo định hướng triển lãm The Living Gallery · Can Tho, VN",
    },
    languageSwitch: { vi: "VI", en: "EN" },
  },
} as const;
